feat: Minor improvements to code style
vd2org/snowflake pull request #8
Opened 2024-04-02 16:11 UTC by Isabe1le

Hiya, I made some improvements to the typing along with updating the module to follow PEP best practices such as using __all__ in the__init__ file & not shadowing variable types on SnowflakeGenerator.__init__

2024-04-02 21:01 UTC, vd2org requested changes
Thank you for your contribution. Reviewed.

2024-04-02 21:01 UTC, vd2org commented on src/snowflake/snowflake.py
> +@dataclass(frozen=True, slots=True)
It's not compatible with 3.8 and 3.9.

https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass

2024-04-02 21:01 UTC, vd2org commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
Why?

2024-04-02 21:21 UTC, Isabe1le commented on src/snowflake/snowflake.py
> +@dataclass(frozen=True, slots=True)
Intresting, good catch.

2024-04-02 21:22 UTC, Isabe1le commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
Raises type errors in newer Python versions.

2024-04-02 21:24 UTC, Isabe1le commented
Updated for <3.10 support.

2024-04-02 21:29 UTC, vd2org commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
Hmmm... specifically?

2024-04-03 10:15 UTC, vd2org commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
Checked on 3.11 and 3.12. No errors there. Did i miss something?

2024-04-03 10:23 UTC, Isabe1le commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
It was raising unknown type errors when using pyright for 3.12.2

2024-04-03 10:34 UTC, vd2org commented on src/snowflake/snowflake.py
> +    def datetime_tz(self, tz: Optional[tzinfo] = None) -> 'datetime':
Can't reproduce it. Could you share full example, please?

2024-08-29 12:51 UTC, closed without merging